<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUgR8KNX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUgR8KNX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUgR8KNX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUgR8KNX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUgR8KNX\App_KernelDevDebugContainer([
    'container.build_hash' => 'UgR8KNX',
    'container.build_id' => 'e4ca1d49',
    'container.build_time' => 1596442134,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUgR8KNX');
