<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW0xPMXv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW0xPMXv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW0xPMXv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW0xPMXv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW0xPMXv\App_KernelDevDebugContainer([
    'container.build_hash' => 'W0xPMXv',
    'container.build_id' => '982c94f4',
    'container.build_time' => 1596181873,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW0xPMXv');
