<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerUgR8KNX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUgR8KNX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUgR8KNX.legacy');
=======
if (\class_exists(\ContainerH7kRN6r\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH7kRN6r/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH7kRN6r.legacy');
>>>>>>> e45df90a1a5d52a4b59e414dbdcff741409fab76

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerUgR8KNX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUgR8KNX\App_KernelDevDebugContainer([
    'container.build_hash' => 'UgR8KNX',
    'container.build_id' => 'e4ca1d49',
    'container.build_time' => 1596442134,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUgR8KNX');
=======
    \class_alias(\ContainerH7kRN6r\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH7kRN6r\App_KernelDevDebugContainer([
    'container.build_hash' => 'H7kRN6r',
    'container.build_id' => 'c5b6f33a',
    'container.build_time' => 1596442304,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH7kRN6r');
>>>>>>> e45df90a1a5d52a4b59e414dbdcff741409fab76
